version: "3"

services: 
  laptop_setup:
    container_name: semantic-corrections
    image: ghcr.io/droid-dataset/droid_laptop:${ROBOT_TYPE}
    shm_size: 4g
    tty: true
    stdin_open: true
    environment:
      ROOT_DIR: ${ROOT_DIR}
      DISPLAY: ${DISPLAY}
      XAUTHORITY: ${DOCKER_XAUTH}
      ROBOT_TYPE: ${ROBOT_TYPE}
      LIBFRANKA_VERSION: ${LIBFRANKA_VERSION}
      NUC_IP: ${NUC_IP}
      ROBOT_IP: ${ROBOT_IP}
      LAPTOP_IP: ${LAPTOP_IP}
      NVIDIA_VISIBLE_DEVICES: all
      ANDROID_ADB_SERVER_ADDRESS: host.docker.internal
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${DOCKER_XAUTH}:${DOCKER_XAUTH}
      - ${ROOT_DIR}/droid:/app/droid
      - ${ROOT_DIR}/scripts:/app/scripts
      - ${ROOT_DIR}/data:/app/data
      - ${ROOT_DIR}/cache:/app/cache
      - /home/robin/workspace/openpi:/app/openpi
      - /home/robin/workspace/arpit/semantic_corrections:/app/semantic_corrections
      - /home/robin/workspace/robotic_failure_data:/app/robotic_failure_data
      - /home/robin/workspace/oopsie-tools:/app/oopsie-tools
    build: 
      context: ../../
      dockerfile: .docker/laptop/Dockerfile.test_laptop
      args:
        ROOT_DIR: ${ROOT_DIR}
        ROBOT_TYPE: ${ROBOT_TYPE}
        NUC_IP: ${NUC_IP}
        ROBOT_IP: ${ROBOT_IP}
    devices:
      - /dev/bus/usb:/dev/bus/usb
    runtime: nvidia
    privileged: true
    network_mode: "host"
    command: bash #python /app/scripts/main.py
